### ISSUE TITLE
upstart script doesn't respect flag only parameter

### ISSUE THREAD

**Issue by activars** [mesosphere/chronos-pkg#9]
I want to enable mail_ssl with the upstart script. When creating an empty file in `conf/mail_ssl` directory, chronos failed to start. 

It seems the script generates a startup command with --mail--ssl '' 

Do you have any known workaround?

**Comment by lloesche** [comment]
Flags are prefixed with ?

E.g.
```
touch conf/?mail_ssl
```

**Comment by activars** [comment]
Thanks, I will try that.
